language: zh-CN

enable:
  subtitle: false

valine:
  enable: false # æ˜¯å¦å¼€å¯ é»˜è®¤falseä¸å¼€å¯
  appid:  # ä½ çš„appid
  appkey: # ä½ çš„appkey
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: ğŸ˜ˆ
  avatar: monsterid # gravatar style
  guest_info: nick,mail,link # custom comment header
  pageSize: 10 # pagination size
